FROM mysql:latest
ENV MYSQL_ROOT_PASSWORD=password
EXPOSE 3306
COPY init.sql /docker-entrypoint-initdb.d/

# FROM mysql:latest

# ENV MYSQL_ROOT_PASSWORD example
# ENV MYSQL_DATABASE example_db

# EXPOSE 3306
